### ISSUE TITLE
Does not display row 1 on R4 Wifi Matrix

### ISSUE THREAD

**Issue by npuckett** [arduino-libraries/ArduinoGraphics#38]
There is an issue using the library with the new led matrix built in to the Uno R4 Wifi. For some reason when using any of the drawing primitives, it doesn't display the top row. It returns the correct screen width and height, but the top row doesn't show.

**Comment by aentinger** [comment]
This has been fixed over here https://github.com/arduino/ArduinoCore-renesas/pull/260 😉

**Comment by npuckett** [comment]
Not sure that is correct. I saw the library update and hoped that was what is was about. However, I get the same behavior unless I'm missing something. For instance the following code displays nothing on the screen, but if I change it to 
`ledScreen.point(0,1);`, I see it. Same with all other primitives.   Unless I'm missing something else in that thread.  Thanks!

```cpp
#include <ArduinoGraphics.h>
#include <Arduino_LED_Matrix.h>

ArduinoLEDMatrix ledScreen;

void setup() 
{
  ledScreen.begin();

  ledScreen.beginDraw();
  ledScreen.stroke(0xFFFFFFFF);
  ledScreen.point(0,0);
  ledScreen.endDraw();
}

void loop() {}
```

**Comment by npuckett** [comment]
Just looked through that thread again and can't find an answer. Is it because the primitives are treated differently than text?

**Comment by aentinger** [comment]
You've misunderstood - you need to update ArduinoCore-renesas, the issue was located within there (see https://github.com/arduino/ArduinoCore-renesas/pull/260/files - it should be crystal clear).

**Comment by npuckett** [comment]
Ah - thanks for following up. Was having one of those weeks, sorry to bring you into it, but I appreciate you taking the time. Great library
