### ISSUE TITLE
Add support for ellipse and circle

### ISSUE THREAD

**Issue by sandeepmistry** [arduino-libraries/ArduinoGraphics#6]
From @tigoe:

>   Add in graphics primitives: ellipse(), circle(), rect(), from Processing/p5.js
> ...
> obviously ellipse() is the key one. circle is just a special case, and arc is less used, though useful for pie chart progress meters, I suppose.

**Comment by ashutoshshrm529** [comment]
Hi I was interested in working on this issue and have written some code for the ellipse function.
@sandeepmistry could you please tell me how I should go about testing the code and what checks I should make?

**Comment by ashutoshshrm529** [comment]
I have written an ellipse function here - https://github.com/arduino-libraries/ArduinoGraphics/pull/9#issue-389165028

Since there is no examples subdirectory in this library, the checks could not run. 
Could the moderators please look into it.
Thank you.
